version: 2
jobs:
  python:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - venv
            - tox-{{ checksum "python/tox.ini" }}

      - run:
          name: install dependencies
          command: |
            cd python/
            python -m venv venv || true
            . venv/bin/activate
            pip install tox

      - save_cache:
          paths:
            - python/venv
          key: venv

      - save_cache:
          paths:
            - python/.tox
          key: tox-{{ checksum "python/tox.ini" }}
  
      - run:
          name: run python tests
          command: |
            cd python/
            . venv/bin/activate
            tox -e py37 -e cov -e codecov

  node:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-{{ checksum "typescript/package.json" }}

      - run:
          name: install dependencies
          command: |
            cd typescript/
            npm install

      - save_cache:
          paths:
            - typescript/node_modules
          key: node_modules-{{ checksum "typescript/package.json" }}

      - run:
          name: run node tests
          command: |
            cd typescript/
            npm test -- --coverage
            npm run codecov

workflows:
  version: 2
  build_and_test:
    jobs:
      - python
      - node
